server:
   port: 8083
   
   
spring:
  application:
      name: api-gateway  
  cloud:
   gateway: 
     routes:
       - id: customer-service
         uri: lb://CUSTOMER-SERVICE
         predicates:
         - Path=/**
       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
          - Path=/**
   
   
   
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
 